export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const LOAD_SAMPLES_SUCCESS = 'LOAD_SAMPLES_SUCCESS';
export const FIND_SAMPLE_SUCCESS = 'FIND_SAMPLE_SUCCESS';
export const UPDATE_SAMPLE_SUCCESS = 'UPDATE_SAMPLE_SUCCESS';
export const CREATE_SAMPLE_SUCCESS = 'CREATE_SAMPLE_SUCCESS';
export const DELETE_SAMPLE_SUCCESS = 'DELETE_SAMPLE_SUCCESS';

//LOGIN ACTIONS
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS =  'LOGOUT_SUCCESS';

export const LOAD_TODO_SUCCESS = 'LOAD_TODO_SUCCESS';
export const SAVE_TODO_SUCCESS = 'SAVE_TODO_SUCESS';
export const CLEAR_TODO_SUCCESS = 'CLEAR_TODO_SUCCESS';

// REGISTRATION ACTIONS
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
